%Setting up all the learning sessions into groups

clear;
%JZ207 Sq maze
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ207';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-08-16',...
                '2018-08-17',...
                '2018-08-23',...
                '2018-08-27',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'sq1',...
            'sq1',...
            'sq1',...
            'sq1',...
            };
save('E:\Data\Endoscope\MetaData\JZ207Sq1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ207 I maze
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ207';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-08-28',...
                '2018-08-29',...
                '2018-08-30',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'linear1',...
            'linear1',...
            'linear1',...
            };
save('E:\Data\Endoscope\MetaData\JZ207I1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');

clear;
%JZ207 T maze
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ207';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-09-10',...
                '2018-09-11',...
                '2018-09-12',...
                '2018-09-14',...
                '2018-09-16',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'tee1',...
            'tee1',...
            'tee1',...
            'tee1',...
            'tee1',...
            };
save('E:\Data\Endoscope\MetaData\JZ207Tee1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ207 circle maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ207';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-09-18',...
                '2018-09-20',...
                '2018-09-24',...
                '2018-09-26',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1,2]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle1',...
            'circle1',...
            'circle1',...
            'circle1',...
            };
save('E:\Data\Endoscope\MetaData\JZ207Circle1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ207 circle maze2
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ207';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-11-29',...
                '2018-11-30',...
                '2018-12-06',...
                '2018-12-09',...
                '2018-12-11',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1,2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle1',...
            'circle1',...
            'circle1',...
            'circle1',...
            'circle1',...
            };
save('E:\Data\Endoscope\MetaData\JZ207Circle2.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ209 circle maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ209';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2018-09-20',...
                '2018-09-24',...
                '2018-09-27',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle1',...
            'circle1',...
            'circle1',...
            };
save('E:\Data\Endoscope\MetaData\JZ209Circle1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');


clear;
%JZ218 circle maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ218';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-01-22',...
                '2019-01-23',...
                '2019-01-25',...
                '2019-01-27',...
                '2019-01-29',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1,2,3]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle1',...
            'circle1',...
            'circle1',...
            'circle1',...
            'circle1',...
            };
save('E:\Data\Endoscope\MetaData\JZ218Circle1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');


clear;
%JZ219 tee maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ219';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-01-19',...
                '2019-01-20',...
                '2019-01-21',...
                '2019-01-22',...
                '2019-01-23',...
                '2019-01-25',...
                '2019-01-27',...
                '2019-01-29',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'tee2',...
            'tee2',...
            'tee2',...
            'tee2',...
            'tee2',...
            'tee2',...
            'tee2',...
            'tee2',...
            };
save('E:\Data\Endoscope\MetaData\JZ219Tee1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ219 circle maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ219';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-02-25',...
                '2019-02-28',...
                '2019-03-04',...
                '2019-03-04',...
                '2019-03-05',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1],[2]},...
                    {[1,2],[3]},...
                    {[1,2],[3]},...
                    {[1,2,3],[4,5]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle2',...
            'circle2',...
            'circle2',...
            'circle2',...
            'circle2',...
            };
save('E:\Data\Endoscope\MetaData\JZ219Circle1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ222 tee maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ222';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-03-04',...
                '2019-03-05',...
                '2019-03-06',...
                '2019-03-07',...
                '2019-03-08',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1,2],[3]},...
                    {[1,2],[3]},...
                    {[1],[2]},...
                    {[1],[2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\JZ222Tee1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ224 circle maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ224';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-03-04',...
                '2019-03-05',...
                '2019-03-06',...
                '2019-03-07',...
                '2019-03-08',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1],[2]},...
                    {[1,2],[3]},...
                    {[1],[2]},...
                    {[1],[2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'circle2',...
            'circle2',...
            'circle2',...
            'circle2',...
            'circle2',...
            };
save('E:\Data\Endoscope\MetaData\JZ224Circle1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ222 tee maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ226';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-03-04',...
                '2019-03-05',...
                '2019-03-06',...
                '2019-03-07',...
                '2019-03-08',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1],[2]},...
                    {[1],[2]},...
                    {[1],[2]},...
                    {[1],[2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\JZ226Tee1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');





clear;
%JZ229 tee maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ229';
resultFolderList = {...
                    'CaImAn_Results_V3',...
                    'CaImAn_Results_V3',...
                    'CaImAn_Results_V3',...
                    'CaImAn_Results_V3',...
                    'CaImAn_Results_V2',...
                    'CaImAn_Results_V2',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-03-22',...
                '2019-03-24',...
                '2019-03-26',...
                '2019-03-28',...
                '2019-03-31',...
                '2019-04-04',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1,2]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'tee3',...
            'tee3',...
            'tee3',...
            'tee3',...
            'tee3',...
            'tee3',...
            };
save('E:\Data\Endoscope\MetaData\JZ229Tee1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ231 h maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-05-24',...
                '2019-05-25',...
                '2019-05-27',...
                '2019-05-28',...
                '2019-05-29',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231H1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ231 h maze2
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-05-30',...
                '2019-05-31',...
                '2019-06-01',...
                '2019-06-02',...
                '2019-06-04',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231H2.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');

clear;
%JZ231 I maze1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-05',...
                '2019-06-06',...
                '2019-06-07',...
                '2019-06-08',...
                '2019-06-10',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1,2]},...
                    {[1,2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231I1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ231 O maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-11',...
                '2019-06-12',...
                '2019-06-13',...
                '2019-06-14',...
                '2019-06-15',...
                '2019-06-17',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231O1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ231 O maze 2
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-18',...
                '2019-06-19',...
                '2019-06-20',...
                '2019-06-21',...
                '2019-06-24',...
                '2019-06-25',...
                '2019-06-26',...
                '2019-06-27',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1]},...
                    {[1,2]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1,2]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231O2.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%JZ231 O maze 3
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-28',...
                '2019-06-29',...
                '2019-07-01',...
                '2019-07-02',...
                '2019-07-03',...
                '2019-07-05',...
                '2019-07-08',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231O3.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');


clear;
%JZ231 O maze all
dataFolder = 'E:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-11',...
                '2019-06-12',...
                '2019-06-13',...
                '2019-06-14',...
                '2019-06-15',...
                '2019-06-17',...
                '2019-06-18',...
                '2019-06-19',...
                '2019-06-20',...
                '2019-06-21',...
                '2019-06-24',...
                '2019-06-25',...
                '2019-06-26',...
                '2019-06-27',...
                '2019-06-28',...
                '2019-06-29',...
                '2019-07-01',...
                '2019-07-02',...
                '2019-07-03',...
                '2019-07-05',...
                '2019-07-08',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1],[2]},...
                    {[1]},...
                    {[1,2]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1,2]},...
                    {[1],[2]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\JZ231Os.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%WG027 T maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG027';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG027S03',...
                'WG027S04',...
                'WG027S05',...
                'WG027S06',...
                'WG027S07',...
                };
sessionBlkAlloList = {...
                    {[1,2],[3],[4]},...
                    {[1,2],[3],[4]},...
                    {[1,2],[3],[4]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3]},...
                    };
sessionBlkNumList = {...
                    2,...
                    2,...
                    2,...
                    2,...
                    2,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\WG027T1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');




clear;
%WG032 T maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG032';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG032S03',...
                'WG032S04',...
                'WG032S05',...
                'WG032S06',...
                'WG032S07',...
                };
sessionBlkAlloList = {...
                    {[1,2],[3],[4]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3]},...
                    {[1,2],[3],[4]},...
                    {[1],[2],[3]},...
                    };
sessionBlkNumList = {...
                    2,...
                    2,...
                    2,...
                    2,...
                    2,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\WG032T1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%WG034 T maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG034';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG034S03',...
                'WG034S04',...
                'WG034S05',...
                'WG034S06',...
                'WG034S07',...
                };
sessionBlkAlloList = {...
                    {[1,2],[3],[4]},...
                    {[1],[2],[3,4]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3]},...
                    };
sessionBlkNumList = {...
                    2,...
                    2,...
                    2,...
                    2,...
                    2,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\WG034T1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');




clear;
%WG035 T maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG035';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks2_Rmin50_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG035S03',...
                'WG035S04',...
                'WG035S05',...
                'WG035S06',...
                'WG035S07',...
                };
sessionBlkAlloList = {...
                    {[1],[2],[3,4]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3]},...
                    {[1],[2],[3,4]},...
                    {[1],[2],[3]},...
                    };
sessionBlkNumList = {...
                    2,...
                    2,...
                    2,...
                    2,...
                    2,...
                    };
mapKeyList = {...
            't1',...
            't1',...
            't1',...
            't1',...
            't1',...
            };
save('E:\Data\Endoscope\MetaData\WG035T1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');





clear;
%WG036 O maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG036';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG036S04',...
                'WG036S05',...
                'WG036S06',...
                'WG036S07',...
                'WG036S08',...
                'WG036S09',...
                'WG036S10',...
                'WG036S11',...
                'WG036S12',...
                'WG036S13',...
                'WG036S14',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\WG036O1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');

clear;
%WG037 O maze 1
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG037';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG037S04',...
                'WG037S05',...
                'WG037S06',...
                'WG037S07',...
                'WG037S08',...
                'WG037S09',...
                'WG037S10',...
                'WG037S11',...
                'WG037S12',...
                'WG037S13',...
                'WG037S14',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\WG037O1.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');



clear;
%WG037 O maze 2
dataFolder = 'E:\Data\Endoscope';
animalID = 'WG037';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                'WG037S15',...
                'WG037S16',...
                'WG037S17',...
                'WG037S18',...
                'WG037S19',...
                'WG037S20',...
                };
sessionBlkAlloList = {...
                    {[1],[2]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            'h1',...
            };
save('E:\Data\Endoscope\MetaData\WG037O2.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');




clear;
%JZ231 H/I maze
dataFolder = 'D:\Data\Endoscope';
animalID = 'JZ231';
resultFolderList = {...
                    'CaImAn_Results_V1',...
                    'CaImAn_Results_V1',...
                    };
resultNameList = {...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    'Isomap_Cnorm_10Hz_Vmin0_Blks1_Rmin100_2D_10_100_5',...
    };
    
sessionIDList = {...
                '2019-06-04',...
                '2019-06-05',...
                };
sessionBlkAlloList = {...
                    {[1]},...
                    {[1]},...
                    {[1]},...
                    };
sessionBlkNumList = {...
                    1,...
                    1,...
                    };
mapKeyList = {...
            'h1',...
            'I1',...
            };
save('D:\Data\Endoscope\MetaData\JZ231HI.mat', 'dataFolder',...
    'animalID','resultNameList','resultFolderList',...
    'sessionIDList','sessionBlkAlloList',...
    'sessionBlkNumList','mapKeyList');

